# Generated by Django 4.1 on 2022-08-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_last_anme_author_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
